#Brayden Woodard, Kian Johnson
#11/2020
#organ trale

def Opening():
    print("""MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxxkxdkkdkXKdxKWXxd0WNkdxOkxdONMMMMMWWXOkOk0NWMW0kO0Ok0NMMMN0kOOkOKWMMMMWOoxKWMMMW0dx0WNOxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxkO:.oOdxXO''OWK;.xNNl.c0KkoOWMMMMWk::lOKOc:OWNc.dXXo'lXWk:cx00xcxNMMMMXl..oNMMMMk'.cKNdc0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNc.xWWWWk.'xKO,.kWXc.:kkkXWMMMMM0, ,OWMMx.:KNc.oKOl,oX0,'dxOK0kOXWMNklod,.lONMM0o:'cKkoXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc.xWMMNd..oxd'.kNK:.:kxkNMMMMMMO. ,0WMMk.,0O,.lx:cONMO.'kK00o':0WMNo,cd:..dXWM0d0d'cooXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc.dNMMM0',0WX;.kWWo.oNMN00WMMMMXc.,xNMNo.lXXc.xNk;oXWNl'oXMMk.:XMW0ldkdxc.cXMMOo0Nx'.lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl;dXWMWO::kNKc;xXXd:oOOxco0WMMMMX0kdkkdlxXWXl;dXXc.l0NNOodO0d;c0N0l;xXWWO:;xXXdckNNx:oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXNWMMNXXXNWNXNNWNNNNNNNNNWMMMMMMMWNXXNWMMWNXNNWKkOXWMMWNXXXXXNNNNXXWMMWNNXNNNXXNWWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOO0OO0OOKWNK0000KWMMMMMMWKOOXWMMMWKO0XMMMMMXOO00OOOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWklxd''ddlxXd'c00d;lXWMMMMXl..dNMMMWx.;0WMMMMK;.okkolOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWK,,0WNNWd.lXNx,:0WWMW0dol.,xKWMMk':XMMMMWK;.dK00NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,,0MMMKc.:xl:dKWMMMNo'cx; 'dXWMk.:XMMMMNk'.lxokNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,,0WMMNl.lXO:oXMMMMKoodll;.oNMMk.:XMWXXWX:.kWWXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,,kWMMNo'cKNo.:0XX0c;xXNNk',xXNx':O0x:oK0c,dOOdcdXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX00KNMMWK00XWKod0XXK00KNMMX00KXNK0000000XXKKKKKKKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xkkkkxxxxddddooooooooookNMMMMMMMMMMMMMMMMMMMK;.dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkooddoddoddooddoooooooooooooooONMMMMMXxoodddddddooddddoxKMMMMMMMX:'loooddddxxxkkkkOOO0KKKXWMMMMMMMMMMMMMMMMMMNl,;,kWMMMMMMMMMMMMMMMMMMWNNMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO':xxxkxxkxxkkxkkOOOOOOOOOOOOOOKWMMMMMO';xxxxxxxxkxxkxxxOXMMMMMMMX::XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,dXl;OMMMMMMMMMMMMMMMMMNx,:0WMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,dMMMMMMMMMMMMMMMMMMMMMMMMX::XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;cXMXc:KMMMMMMMMMMMMMMMXo;;'cOKNMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,dMMMMMMMMMMMMMMMMMMMMMMMMX::XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl;0MMM0;cXMMMMMMMMMMMMMKc:OK:;kOk0NWWNK0XWMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,dMMMMMMMMMMMMMMMMMMMMMMMMX::XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,xWMMMMO;oNMMMMMMMMMMWO:cKMWd,kWXOOOOOOKNMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,dMMMMMMMMMMMMMMMMMMMMMMMMNc;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;cNMMMMMWx,dWMMMMMMMMNx;oXMMM0;lNMMNNNWMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,dMMMMMMMMMMMMMMMMMMMMMMMMWl,ONNNXXKK00OOkkxxxdddood0WMMMMMMMMMMMMMNl;0MMMMMMMNo,kWMMMMMMXl;xWMMMMNl;KMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,dMMMMMMMMMMMMMMMMMMMMMMMMWl.:ooloooooooooodddxxxkOOXWMMMMMMMMMMMMWx,xWMMMMMMMMNl;OMMMMM0c:OWMMMMMMk;xMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,dMMMMMMMMMMMMMMMMMMMMMMMMWl,ONNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;lNMMMMMMMMMMK::KMMWk;cKMMMMMMMMXooKWMMMWN0XWMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,dMMMMMMMMMMMMMMMMMMMMMMMMWl;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc;0MMMMMMMMMMMM0;cXNd;oNMMMMMMMMMWd,lOXWNKkONMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,dMMMMMMMMMMMMMMMMMMMMMMMMWo,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,xWMMMMMMMMMMMMWk;:c;kWMMMMMMMMMMMO,l0OOOOKWMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,dMMMMMMMMMMMMMMMMMMMMMMMMWd,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;lNMMMMMMMMMMMMMMWx,:0WMMMMMMMMMMMMXc:KWNNWMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,oNNNNXXXKK000OOO0NMMMMMMMWd,OMMMMMMMMMMWWWWNNNXXXKXWMMMMMMMMMMXc;KMMMMMMMMMMMMMMMMWXNMMMMMMMMMMMMMMWx,kMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,xNNNNNNNNNXXXXXXXXXKKKKKKKKKKKNMMMMMO;;loooooooooooooodKMMMMMMMWd.:ddooooooooooooooooooodKMMMMMMMMMWd,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;lNMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO:coooloooooooooooooooooooooooodKMMMMMWXXNNWWWWWWMMMMMMMMMMMMMMMMWd.cxxkkOOO00KKXXXNNWWWWWMMMMMMMMMMMXoxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNolXMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNNNNWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNWMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0000XXXXKKXXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX000KNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM""")
Opening()
input()

def menu():
    print("""  'c:looddoocc:.'l;                                 .;loooooo:.                                                                           'c:lodddooc::.                                  .:l.          
      'oc;,:xo,,:oc..lc                                'dl;,,,,,,cdc.                                                                         ,oc;,:xo,,:oc.                                   'o;          
       .oc       :c                                :l.        ;l.                                                                              .oc                                   ..    .l;          
       ;xo.      :o,.....     ........            .od'       .ld, ........'..   ..'...'.     ......,:c,    ..'.....   ..........               ;xo.     ..........    ....'...      .;.    .l;          
       .l:       cxc,,,;cc.  ;l:,,,,;lc.          .ld'       .cd, .:ll:;,,;l:. ,l:;,,,;cc.  ;dc;,,;;:ld'  ,l:,,,,;cc. .:ll;,,;:l,              .l;      .:ll;,,,:o;  .;;;;,,;lc.    ,d:    .l;          
       .l;       cl.    ,o' .lo,,,,,,lc.           :l.        ;l.  .l:         cd;,,,,,cl.  :d:,,,,,,ld' .cc.     .o;  'o;    .cc.             .l;       .o;         'c:;;;;;od'    .cc    .l;          
       'dc.     .lo.    ;d; .ld;,,,,;;.            ;d:.......,dl.  .oc.        cx:,,,,,;'   ;dlccccccc,   cl.     'o,  ,d:    .lo.             'dc.      'd:        .ld'.....lx,    .ol.   .o:          
      '::c;.    'cc,   .:c:. .::;;;;;;.             'clollooll;.   ,cc'        .::;;;;;;'   :dc::::::cl.  .::;;;;;;,. .;c:.   'cc,            '::c;.    .;c:.        .::;;;;;ccc'   ,cc'  .;c:.         
                                                                                            'c;;;;;;,::.                                                                                                
                                                                                                                                                                                                        
     ..       ..                                                                               ....                                                                                ..       ..          
      ......';;,...                                     ...    ..                           ..',;;,''..                           ...   ...                                     ...,;;'......           
         ...',;;;,,''..........................................''..............................',,'................................'..........................................'',,;;;;,....             
              ...                                      .......... .......'...........'.......................'...................   ........                                      ...                   
                                                         ................             .....   ........  .....             ................                                                              
                                                                                         ......    .......      """       )                                                                                 
                                                                                                                                                                                                        
    options = [   "Travel the trail", "Learn about the trail","Quit Game"]
    while True:
        choice = menu_display(options)
        if choice== 1:
            break
        if choice== 2:
            learn()
        if choice== 3:
           quit()
    play()
    
        
def  menu_display(options):
    index = 1
    for option in options:
        print(str.format("{}. {}",index,option))
        index+=1

    while True:
        x = input("enter a number between 1 and "+ str(len(options)))
        if x.isnumeric():
            x=int(x)
            if x >= 1 and x<=len(options):
                return x
            else:
                print("not a good choice")
        else:
            print("not a good choice")
                      


def learn():
    learntext=["""try taking a journey by
    covered wagon across 2000
    miles of plains, rivers, and
    mountains. Try! on the
    plains, will you slosh your
    oxen through mud and
    water-filled ruts or will you
    plod through dust six inches deep?""",
               """how will you cross the river?
    if you have money, you might
    take a ferry (if there is a
    ferry). or, you can ford the
    river and hope you and your
    wagon arent swallowed alive!""",
               """What about the supples? well, if
    you're low on food you can
    hunt. you might get a buffalo...
    you might. and there are
    bears in the mountains""",
               """At the dalles, you can try 
    navigating the columbia river,
    but if running the rapids with
    a makeshift raft makes you
    pueasy, better take the barlow
    road.""",
               """if for some reason you dont
    survive -- your wagon burns,
    or thieves steal your oxen, or
    you run out of provisions, or
    you die of cholera -- dont
    give up! try again... and
    again... until your name is up
    with the other on the oregon top ten.""",
               """You may turn the sound on or
    off during the program by
    pressing Control-S""",
               """You may want to puit in the
    middle of the program. if so,
    press the escape (ESC) key
    twice whenever the computer is
    waiting for a responce.""",
               """The software team responsible
    for creation of this product includes:
     Kian Johnson, Brayden Woodard"""]
    for text in learntext:
        print(text)
        input()
        
        
def getname():
    while True:
        name=input(question)
        if name.isnumeric() ==False:
            if len(name)>=1:
                return name
            print("not a good name")



def getnumber(question,low,high):
    while True:
        number=input(question)
        if number.isnumeric():
            number=int(number)
            if number >=low and number <=high:
                return number
            print("not a good number")
  
def familysetup():
  wagonleader=getname(question)
  
x = getnumber("testing",2,5)
print(x)
getname(question)
print(name)

#the shopping system for the use to buy things for there journey   
def shop(money):
    ammo = 0
    food = 0
    clothes = 0
    ox = 0
    parts = []
    bill = 0
    items = ["Oxen", "food", "ammo",
             "clothes", "waggon parts",
             "check out"]
    spent_on_items = [0.00,0.00,0.00,0.00,0.00,bill]
    print("before leaving independence you should buy equipment and supplies.")
    print(str.format("you have{} in cash to make this trip",money))
    print("remember you can buy supplies along the way so you dont have to spend it all now")
    print()
    print()
    input("press any key to continue")
    while True:
        spent_on_items[len(spent_on_items)-1] = bill
        print("welcome to the generel shop")
        print("here is a list of things you can buy")
        print()
        print("============================================")
        for i in range(len(items)):
            print(str.format("\t{}:    {:20}    ${:.2f}",i+1,items[i],spent_on_items[i]))
        print("============================================")
        print()
        print(str.format("total bill so far:      ${:.2f}",bill))
        print(str.format("total funds avalable:   ${:.2f}",money-bill))
        choice = int(input("what do you want to buy"))#use get_number function not input
        if choice == 1:
            print("""
            there are 2 oxen in a yoke;
            i recomend at least 3 yokes.
            i charge $40 a yoke""")
            print(str.format("total bill so far:        ${:.2f}",bill))
            answer = int(input("how many yoke do you want"))
            cost = answer*40
            bill += cost
            ox = answer * 2
            spent_on_items[0] = cost
            
        if choice == 2:
            print("""
            i recomend 200 pounds of food
            pure person.
            i charge .20 a pound""")
            print(str.format("total bill so far:       ${:.2f}",bill))
            answer = int(input("how much food do you want"))
            cost = answer*.2
            bill += cost
            food = answer * 1
            spent_on_items[1] = cost
            
        if choice == 3:
            print("""
            1 box equals 20 bullets.
            1 box is 2.00 a box""")
            print(str.format("total bill so far:       ${:.2f}",bill))
            answer = int(input("how much boxes of ammo would you like"))
            cost = answer*2.00
            bill += cost
            ammo = answer * 1
            spent_on_items[2] = cost
            
        if choice == 4:
            print("""
            1 set of clothes is 10.00.
            i recomend 2 sets a person""")
            print(str.format("total bill so far:       ${:.2f}",bill))
            answer = int(input("how much clothing do you want"))
            cost = answer*10.00
            bill += cost
            clothes = answer * 1
            spent_on_items[3] = cost
        if choice == 5:
            inventory = []
            print("""
            it is a good idea to have a few
            spare parts for your wagon on hand
            you never know what can happen on
            the trail and a broken down
            wagon can be a death sentance.""")
            parts_bill = 0.00
            parts = ["wagon wheel", "wagon axle","wagon tongue","back to main shop"]
            parts_cost =[10.00,20.00,50.00,parts_bill]
            while True:
                parts_cost[len(parts_cost)-1] = parts_bill
                print("here is a list of things you can buy")
                for i in range(len(parts)):
                     print(str.format("{}.   {:20}     ${:.2f}",i+1,parts[i],parts_cost[i]))
                print(str.format("Total bill so far:        ${:.2f}",bill))
                print(str.format("total funds avalable:     ${:.2f}",money))
                item = int(input("What Item would you like to buy"))
                if item == 1:
                    answer = int(input("how many wagon Wheels do you want?"))
                    for i in range(answer):
                        inventory.append("Wagon Wheel")
                    parts_bill += parts_cost[0] * answer
                elif item == 2:
                    answer = int(input("how many Wagon axles do you want?"))
                    for i in range(answer):
                        inventory.append("Wagon axle")
                    parts_bill += parts_cost[1]*answer

                elif item == 3:
                    answer = int(input("how many Wagon Tongues do you want?"))
                    for i in range(answer):
                        inventory.append("wagon tongue")
                    parts_bill += parts_cost[2]*answer
                elif item == 4:
                    bill +=parts_bill
                    spent_on_items[4] = parts_bill
                    break
                
                        
                                      
                
        if choice == 6:
            if bill <= money:
                money -= bill
                return ox, food,clothes,inventory
            else:
                print("you dont have that much money alter your shoping list")

money=1000
food = 0
ammo = 0
cloths = 0
parts = []
ox = 0
shop(money)

def travel (health, pace, weather):
    import random
    mph = 0
    weather_mod = 0
    hours = 0

    
    if pace == "normal":
        mph = 2
    elif pace == "slow":
        mph = 1
    elif pace == "fast":
        mph = 4

    if health == "bad":
        hours = 4
    elif health == "good":
        hours = 8
    elif health == "decent":
        hours = 6

    if weather == "blizzard":
        weather_mod = 0
    elif weather == "hot":
        weather_mod = .5
    elif weather == "rain":
        weather_mod = .25
    elif weather == "comftorable":
        weather_mod = 1

    miles = hours * mph * weather_mod
    random_mod = random.randint(0,5)
    return miles - random_mod

miles = travel(health, pace, weather)

  
#game starts
Opening()   
menu()       
  



